version: '3.9'

services:
  app:
    container_name: parqueadero-api-container
    image: parqueadero-api
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      HOST: mysql-db
      PORT: 3000
    networks:
      - parqueadero-network
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    image: mysql:8.0.37-bookworm
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parqueaderodb
    ports:
      - "3308:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - parqueadero-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 2m

volumes:
  mysql-volume:

networks:
  parqueadero-network:
    driver: bridge